# Welcome to !
#

# Site settings
title: FDDeveloper
description: |
  Be an idealistic programmer－－FDD
owner: 张东 # or company name
first_published: 2016 # if migrating another site, the year of your first publish
email: 975186901@qq.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://fdlove.github.io/" # the base hostname & protocol for your site
social:
  twitter: https://github.com/FDlove
  github: https://github.com/FDlove
  linkedin-square: https://github.com/FDlove
  facebook-official: https://github.com/FDlove
  google-plus-square: https://github.com/FDlove
  #email: /contact/
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
